WEB/Controllers/ArquivoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WEB.Models;
using WEB.Repositories.Interfaces;
using WEB.ViewModels;

namespace WEB.Controllers
{
    public class ArquivoController : Controller
    {
        private readonly IArquivoRepository _arquivoRepository;
        public ArquivoController(IArquivoRepository ArquivoRepository)
        {
            _arquivoRepository = ArquivoRepository;
        }

        [HttpGet]
        [Authorize]
        public IActionResult Lista()
        {
            ArquivosListaViewModel arquivosListaViewModel = _arquivoRepository.ListaArquivos();
            return View(arquivosListaViewModel);
        }

        [HttpGet]
        [Authorize]
        public IActionResult Novo()
        {
            Arquivo arquivo = new Arquivo();
            ViewBag.ListaClientes = _arquivoRepository.ListaClientes();
            return View(arquivo);
        }
   
        [HttpPost]
        [Authorize(Roles = "usu,adm,mst")]
        public IActionResult Novo(Arquivo arquivo)
        {
            int idArquivoSalvo = _arquivoRepository.NovoArquivo(arquivo);
            return RedirectToAction("Detalhe", new { arquivoId = idArquivoSalvo });
        }

        [HttpGet]
        [Authorize]
        public IActionResult Detalhe(int arquivoId)
        {
            ArquivosViewModel arquivosViewModel = _arquivoRepository.ArquivoDetalheId(arquivoId);
            return View(arquivosViewModel);
        }

        [HttpGet]
        [Authorize]
        public IActionResult Editar(int arquivoId)
        {
            Arquivo arquivo = _arquivoRepository.ArquivoId(arquivoId);
            ViewBag.ListaClientes = _arquivoRepository.ListaClientes();
            return View(arquivo);
        }

        [HttpPost]
        [Authorize(Roles = "usu,adm,mst")]
        public IActionResult Editar(Arquivo arquivo)
        {
            _arquivoRepository.ArquivoEdita(arquivo);
            return RedirectToAction("Detalhe", new { arquivoId  = arquivo.ArquivoId});
        }

        [HttpGet]
        [Authorize(Roles = "usu,adm,mst")]
        public IActionResult NovaOp(int arquivoId)
        {
            ArquivoOp arquivoOp = new ArquivoOp();
            arquivoOp.ArquivoId = arquivoId;
            return View(arquivoOp);
        }

        [HttpPost]
        [Authorize(Roles = "usu,adm,mst")]
        public IActionResult NovaOp(ArquivoOp arquivoOp)
        {
            _arquivoRepository.NovaOp(arquivoOp);
            return RedirectToAction("Detalhe", new { arquivoId =arquivoOp.ArquivoId});
        }

        [HttpGet]
        [Authorize]
        public IActionResult EditarOp(int opId)
        {
            ArquivoOp arquivoOp = _arquivoRepository.OpId(opId);   
            return View(arquivoOp);
        }

        [HttpPost]
        [Authorize(Roles = "usu,adm,mst")]
        public IActionResult EditarOp(ArquivoOp arquivoOp)
        {
            _arquivoRepository.OpEdita(arquivoOp);
            return RedirectToAction("Detalhe", new { arquivoId = arquivoOp.ArquivoId });
        }

        [HttpGet]
        [Authorize]
        public IActionResult DeleteOp(int opId, int arquivoId, string usuario)
        {
            _arquivoRepository.OpDelete(opId, arquivoId, usuario);
            return RedirectToAction("Detalhe", new { arquivoId = arquivoId });
        }

        [HttpGet]
        [Authorize]
        public IActionResult NovoItem(int arquivoId)
        {
            ArquivoItem arquivoItem = new ArquivoItem
            {
                ArquivoId = arquivoId
            };

            ViewBag.ListaTipos = _arquivoRepository.ListaTipoArquivos();
            return View(arquivoItem);
        }

        [HttpPost]
        [Authorize(Roles = "usu,adm,mst")]
        public IActionResult NovoItem(ArquivoItem arquivoItem)
        {
            _arquivoRepository.NovoItem(arquivoItem);
            return RedirectToAction("Detalhe", new { arquivoId = arquivoItem.ArquivoId });
        }

        [HttpGet]
        [Authorize]
        public IActionResult EditarIItem(int arquivoItemId)
        {
            ArquivoItem arquivoItem =  _arquivoRepository.ItemId(arquivoItemId);
            ViewBag.ListaTipos = _arquivoRepository.ListaTipoArquivos();
            return View(arquivoItem);
        }

        [HttpPost]
        [Authorize(Roles = "usu,adm,mst")]
        public IActionResult EditarIItem(ArquivoItem arquivoItem)
        {
            _arquivoRepository.ItemEdita(arquivoItem);
            return RedirectToAction("Detalhe", new { arquivoId = arquivoItem.ArquivoId });
        }

        [HttpGet]
        [Authorize(Roles = "usu,adm,mst")]
        public IActionResult DeleteItem(int arquivoItemId, int arquivoId, string usuario)
        {
            _arquivoRepository.ItemDelete(arquivoItemId, arquivoId, usuario);
            return RedirectToAction("Detalhe", new { arquivoId = arquivoId });
        }

        [HttpPost]
        [Authorize]
        public IActionResult Pesquisa(ArquivosListaViewModel arquivosListaViewModel)
        {
            ArquivosListaViewModel retorno =  _arquivoRepository.PesquisaArquivo(arquivosListaViewModel);

            if (retorno.Arquivos.Count() == 0)
                ViewBag.Lista = false;
  
            return View("Lista", retorno);
        }
    }
}

WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/WEB.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="~/img/PromoIconeColor.svg" rel="shortcut icon" type="image/x-icon">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="border-bottom: solid 5px #2498d1;">
            <div class="container-fluid">
                <img class="icone-web mb-2 mt-2" src="~/img/Intranet_White.svg" />
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse float-end" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" asp-controller="Arquivo" asp-action="Lista">Arquivos</a>
                        </li>

                        @if (User.IsInRole("mst") || User.IsInRole("adm"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" asp-controller="Usuario" asp-action="Usuarios">Usuários</a>
                            </li>
                        }

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Gabaritos
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#">Cadernos</a></li>
                                <li><a class="dropdown-item" href="#">Calendários</a></li>
                                <li><a class="dropdown-item" href="#">Envelopes</a></li>
                                <li><a class="dropdown-item" href="#">Folders</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="#">Novo Gabarito</a></li>
                                <li><a class="dropdown-item" href="#">Novo Categoria</a></li>
                            </ul>
                        </li>
                    </ul>

                    <ul class="navbar-nav float-sm-end">
                        <li class="nav-item dropdown float-end">
                            <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                <svg style="margin: 0px 5px 0px 0px" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                                    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z" />
                                    <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z" />
                                </svg>
                                @User.Identity.Name.ToUpper()
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" asp-controller="Login" asp-action="Sair">Sair</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <script src="https://unpkg.com/ionicons@4.5.10-0/dist/ionicons.js"></script>
</body>
</html>